# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a15092364f8b19da311b7af02b088e2"
name = "Export-order"
application_url = "https://order-export.onrender.com"
embedded = true
handle = "export-order-13"

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_cart_transforms,read_all_checkout_completion_target_customizations,read_analytics,read_app_proxy,read_assigned_fulfillment_orders,read_cart_transforms,read_channels,read_companies,read_custom_fulfillment_services,read_customer_data_erasure,read_customer_merge,read_customers,read_delivery_customizations,read_delivery_option_generators,read_discounts,read_discounts_allocator_functions,read_discovery,read_draft_orders,read_fulfillment_constraint_rules,read_fulfillments,read_gift_card_transactions,read_gift_cards,read_inventory,read_inventory_shipments,read_inventory_shipments_received_items,read_inventory_transfers,read_locales,read_locations,read_markets,read_merchant_managed_fulfillment_orders,read_metaobject_definitions,read_metaobjects,read_order_edits,read_orders,read_payment_customizations,read_payment_terms,read_price_rules,read_product_feeds,read_product_listings,read_products,read_publications,read_purchase_options,read_returns,read_script_tags,read_shipping,read_shopify_payments_accounts,read_shopify_payments_bank_accounts,read_shopify_payments_disputes,read_shopify_payments_payouts,read_store_credit_account_transactions,read_store_credit_accounts,read_third_party_fulfillment_orders,read_translations,unauthenticated_read_product_inventory,write_all_checkout_completion_target_customizations,write_app_proxy,write_assigned_fulfillment_orders,write_cart_transforms,write_channels,write_companies,write_custom_fulfillment_services,write_customer_data_erasure,write_customer_merge,write_customers,write_delivery_customizations,write_delivery_option_generators,write_discounts,write_discounts_allocator_functions,write_discovery,write_draft_orders,write_fulfillment_constraint_rules,write_fulfillments,write_gift_card_transactions,write_gift_cards,write_inventory,write_inventory_shipments,write_inventory_shipments_received_items,write_inventory_transfers,write_locales,write_locations,write_markets,write_merchant_managed_fulfillment_orders,write_metaobject_definitions,write_metaobjects,write_order_edits,write_orders,write_payment_customizations,write_payment_terms,write_price_rules,write_product_feeds,write_product_listings,write_products,write_publications,write_purchase_options,write_returns,write_script_tags,write_shipping,write_shopify_payments_disputes,write_store_credit_account_transactions,write_third_party_fulfillment_orders,write_translations"

[auth]
redirect_urls = [
  "https://order-export.onrender.com/auth/callback",
  "https://order-export.onrender.com/auth/shopify/callback",
  "https://order-export.onrender.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
